CREATE TABLE PRICES (
    PRICE_LIST INT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    BRAND_ID INT NOT NULL,
    PRIORITY INT,
    CURR VARCHAR(10),
    PRICE DOUBLE,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP
);

CREATE INDEX idx_prices_lookup
ON PRICES (PRODUCT_ID, BRAND_ID, START_DATE, END_DATE, PRIORITY DESC);
